### ISSUE TITLE
Intermittent skipping of platform/console or game/ROM

### ISSUE THREAD

**Issue by Wetzel402** [Weestuarty/simcar-es-de#2]
I did some testing with this theme vs other installed themes and for some reason when using this theme I get intermittent skipping of a platform/console or game/ROM.  Some of my other installed these do not appear to do this. 

ES-DE 2.0.0
Windows 11
Running on a MELE Quieter 2

Thanks!

**Comment by Weestuarty** [comment]
This shouldnt happen, skipping of platform or rom would be down to ESDE itself, the theme has no control over the actual program. Ill report this to Dev, also for any issues its best to raise via discord server as its the most active area for support.

**Comment by Weestuarty** [comment]
https://discord.gg/tvUChye6

Raised with dev but would need more info, please join server via link and raise in support

**Comment by Wetzel402** [comment]
I wanted to add information so that if someone else has this problem and sees this issue they are informed.. 

```
LeonSe — Today at 11:07 AM
It's not simply stuttering? This theme is very demanding and until I've written a new texture cache manager it will introduce stuttering on weaker machines.
```

My machine is a low power fanless PC so this is likely related to performance.
